
[[dicts]]
name="小学館デジタル大辞泉"
path="/Users/iamshijun/Library/Eudb_en_free/DJS.mdx"

[[dicts]]
name="明鏡国語辞典［第三版］"
path="/Users/iamshijun/Library/Eudb_en_free/（大修館）明鏡国語辞典［第三版］.mdx"

[[dicts]]
name="新明解国語辞典 第八版"
path="/Users/iamshijun/Library/Eudb_en_free/smk8.mdx"


[[dicts]]
name="三省堂国語辞典 第八版"
path="/Users/iamshijun/Library/Eudb_en_free/sankoku8.mdx"


[[dicts]]
name="大辞林第四版"
path="/Users/iamshijun/Library/Eudb_en_free/daijirin2.mdx"

[[dicts]]
name="広辞苑第六版"
path="/Users/iamshijun/Library/Eudb_en_free/広辞苑第六版.mdx"

[[dicts]]
name="精選版 日本国語大辞典"
path="/Users/iamshijun/Library/Eudb_en_free/jxbrgd.mdx"

[[dicts]]
name="新世纪日汉双解大词典"
path="/Users/iamshijun/Library/Eudb_en_free/xsjrihanshuangjie.mdx"

[[dicts]]
name="講談社日中"
path="/Users/iamshijun/Library/Eudb_en_free/講談社日中.mdx"

[[dicts]]
name="小学館 日中辞典"
path="/Users/iamshijun/Library/Eudb_en_free/小学館 日中辞典〔中日+同义词反查〕.mdx"